export  interface vacancyType {
    title: string;
    total_position: number;
    responsibility: string[];
    requirement: string[];
    other: any; 
}


export  const vacancy: vacancyType[] = [
    {
        title:"FrontEnd Engineer",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"BackEnd Engineer",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"Devops Engineer",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"Digital Marketing Specialist",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"FullStack Engineer",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"UI/UX Desginer",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"Project Manager",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    },
    {
        title:"Bussiness Development Manager",
        total_position:2,
        responsibility:[
             "Lead the delivery of high quality, innovative, flexible, cost-optimized, and scalable technical solutions that meet business requirements",
             "Design, Develop, test, and maintain software applications with MVC architectures, Microservices, and scalable cloud-native apps.",
            "Perform hands-on coding and provide thoughtful code reviews",
             "Mentor and lead team members to continuously improve quality and productivity of deliverables",
             "Demonstrate ability to work within an agile team as well as collaborate with many other teams on design and implementation strategies. Follow SCRUM Agile Development methodology",
             "Effective Communication Skills- An ability to express your ideas to the recipient & Co-ordinate and communicate with cross-functional team along with the client's team",
             "Problem Solving, Hustler - Get Stuff Done, Self-Disciplined Open-minded, User-Focused, Adaptive",
             "Lean Principles & Analytical Thinking",
             "Project planning, timelines, and milestones for execution and deliverables",
            "Participate in the Evaluation Review of your team member",
        ],
        requirement:[
            "Experience in building an enterprise web application using ReactJS as the frontend framework",
            "Experience with Redux and React Hooks",
            "Expert in HTML5, CSS3",
            "Experience in Bootstrap4 or CSS pre-processor like Less or Sass is highly desirable",
            "Strong knowledge of best practices and modern web design trends is necessary.",
            "Some experience with modern web-based typography.",
            "Excel at rapid prototyping and at writing good code.",
            "Experience with testing/debugging in multiple browsers and platforms.",
            "Expertise in using JavaScript",
            "Should have worked on REST client and WebSockets",
            "Should be able to write Unit testing using any one of the frameworks like Cypress, Jasmine, Karma, Jest, Enzyme, or any other similar framework.",
            "Should have experience in either one of the Build scripts like Gulp or Grunt or Webpack",
            "Low-Latency UI, Page optimization, and bundle build+caching",
            "Problem-solving and debugging skills",
            "Component-based architecture",
        ],
        other:"",
    }
]

